# Use the official Node.js LTS image as the base image
FROM node:latest AS development

RUN npm install -g @nestjs/cli

WORKDIR /usr/src/app

COPY package*.json ./

# RUN npm install glob rimraf

RUN npm install

# RUN npm install --only=development

COPY . .

# RUN npx prisma generate

# RUN nest build

# Set the development stage as the final stage
FROM development AS final

CMD ["npm", "start:dev"]
